# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f9f2737089ed20d8d0f450d2f7b7f678e450ec710708bd4bf7ae07dadf2c996322e6b59ddc0920144f8a25afe3cb359fac9f463ff0cbcc9290aa51a6318c5c6

test:
  secret_key_base: 6cccdd65b52b4f12d22ff5e51eaa908239e2c9ed8ae9e7e3a1f767c8e2ef74b52c6605b2c64269ba26b745f27b227a2759fbab20521bd37b40bcabbfabe75598

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
